{{- if .Values.armtlsMesh.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "armtls-mesh.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armtls-mesh.labels" . | nindent 4 }}
{{- end }}
