{{- if .Values.armtlsMesh.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "armtls-mesh.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armtls-mesh.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "armtls-mesh.selectorLabels" . | nindent 6 }}
{{- end }}
