//go:build !c8s_node

package main

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestRenderValuesEmitsComputedBundle(t *testing.T) {
	render := func(t *testing.T, args ...string) map[string]any {
		t.Helper()
		f := newFakeBin(t)
		f.tool(t, "helm", helmShowValuesBody)
		var err error
		out := captureStdout(t, func() {
			err = runC8s(t, args...)
		})
		if err != nil {
			t.Fatalf("render-values %v: %v", args, err)
		}
		if !strings.Contains(out, "Generated by `c8s render-values`") {
			t.Errorf("output missing the provenance header:\n%s", out)
		}
		var tree map[string]any
		if err := yaml.Unmarshal([]byte(out), &tree); err != nil {
			t.Fatalf("output is not a values.yaml: %v\n%s", err, out)
		}
		return tree
	}

	t.Run("node-metal plumbs platform and distro", func(t *testing.T) {
		tree := render(t, "render-values", "--cvm-mode=node-metal", "--resolve-digests=false", "--distro", "rke2")
		if got := treeAt(t, tree, "platform"); got != "snp" {
			t.Errorf("platform = %#v, want snp", got)
		}
		// No cluster, no digests: every chart component pins its tag instead, at
		// the unstamped-build fallback tag.
		for _, prefix := range [][]string{
			{"image", "tag"}, {"cds", "image", "tag"}, {"attestationApi", "image", "tag"},
			{"ratlsMesh", "image", "tag"}, {"nriImagePolicy", "image", "tag"}, {"volumed", "image", "tag"},
		} {
			if got := treeAt(t, tree, prefix...); got != "main" {
				t.Errorf("%s = %#v, want main", strings.Join(prefix, "."), got)
			}
		}
		// --distro plumbs the chart's single top-level distro value.
		if got := treeAt(t, tree, "distro"); got != "rke2" {
			t.Errorf("distro = %#v, want rke2", got)
		}
	})

	t.Run("aks renders the az-snp platform", func(t *testing.T) {
		tree := render(t, "render-values", "--cvm-mode=aks", "--resolve-digests=false")
		if got := treeAt(t, tree, "platform"); got != "az-snp" {
			t.Errorf("platform = %#v, want az-snp", got)
		}
	})

	t.Run("node-image has no distro value to plumb", func(t *testing.T) {
		tree := render(t, "render-values", "--cvm-mode=node", "--resolve-digests=false", "--distro", "rke2")
		if _, ok := tree["distro"]; ok {
			t.Errorf("distro = %#v; node-image renders RKE2 by construction and has no distro value", tree["distro"])
		}
		if got := treeAt(t, tree, "platform"); got != "snp" {
			t.Errorf("platform = %#v, want snp", got)
		}
	})
}

func TestRenderValuesRequiresCvmMode(t *testing.T) {
	f := newFakeBin(t)
	f.tool(t, "helm", helmShowValuesBody)
	out := captureStdout(t, func() {
		if err := runC8s(t, "render-values", "--resolve-digests=false"); err == nil {
			t.Error("want error without --cvm-mode")
		}
	})
	if out != "" {
		t.Errorf("failed render must emit no bundle, got:\n%s", out)
	}
}

func TestRenderValuesRejectsDebugOutsidePod(t *testing.T) {
	f := newFakeBin(t)
	f.tool(t, "helm", helmShowValuesBody)
	err := runC8s(t, "render-values", "--cvm-mode=node", "--debug", "--resolve-digests=false")
	if err == nil || !strings.Contains(err.Error(), "--cvm-mode=pod") {
		t.Fatalf("want the debug-outside-pod error, got %v", err)
	}
}

func TestRenderValuesRequiresHelm(t *testing.T) {
	newFakeBin(t)
	err := runC8s(t, "render-values", "--cvm-mode=node", "--resolve-digests=false")
	if err == nil || !strings.Contains(err.Error(), "helm CLI not found") {
		t.Fatalf("want a helm-not-found error, got %v", err)
	}
}
