//go:build !c8s_node

package main

import (
	"reflect"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestRenderValuesEmitsComputedBundle(t *testing.T) {
	f := newFakeBin(t)
	f.tool(t, "helm", helmShowValuesBody)

	var err error
	out := captureStdout(t, func() {
		err = runC8s(t, "render-values", "--cvm-mode=node", "--resolve-digests=false", "--distro", "rke2")
	})
	if err != nil {
		t.Fatalf("render-values: %v", err)
	}
	if !strings.Contains(out, "Generated by `c8s render-values`") {
		t.Errorf("output missing the provenance header:\n%s", out)
	}

	var tree map[string]any
	if err := yaml.Unmarshal([]byte(out), &tree); err != nil {
		t.Fatalf("output is not a values.yaml: %v\n%s", err, out)
	}
	if got := treeAt(t, tree, "attestationApi", "cvmMode"); got != "node" {
		t.Errorf("attestationApi.cvmMode = %#v, want node", got)
	}
	if got := treeAt(t, tree, "attestationApi", "teeDevices", "sevGuest"); got != true {
		t.Errorf("teeDevices.sevGuest = %#v, want true", got)
	}
	// No cluster, no digests: every chart component pins its tag instead, at
	// the unstamped-build fallback tag.
	for _, prefix := range [][]string{
		{"image", "tag"}, {"cds", "image", "tag"}, {"attestationApi", "image", "tag"},
		{"ratlsMesh", "image", "tag"}, {"nriImagePolicy", "image", "tag"},
	} {
		if got := treeAt(t, tree, prefix...); got != "main" {
			t.Errorf("%s = %#v, want main", strings.Join(prefix, "."), got)
		}
	}
	// --distro plumbs both component distro keys.
	if got := treeAt(t, tree, "kata", "distro"); got != "rke2" {
		t.Errorf("kata.distro = %#v, want rke2", got)
	}
	if got := treeAt(t, tree, "nriImagePolicy", "distro"); got != "rke2" {
		t.Errorf("nriImagePolicy.distro = %#v, want rke2", got)
	}
}

func TestRenderValuesRequiresCvmMode(t *testing.T) {
	f := newFakeBin(t)
	f.tool(t, "helm", helmShowValuesBody)
	out := captureStdout(t, func() {
		if err := runC8s(t, "render-values", "--resolve-digests=false"); err == nil {
			t.Error("want error without --cvm-mode")
		}
	})
	if out != "" {
		t.Errorf("failed render must emit no bundle, got:\n%s", out)
	}
}

func TestRenderValuesRejectsDebugOutsidePod(t *testing.T) {
	f := newFakeBin(t)
	f.tool(t, "helm", helmShowValuesBody)
	err := runC8s(t, "render-values", "--cvm-mode=node", "--debug", "--resolve-digests=false")
	if err == nil || !strings.Contains(err.Error(), "--cvm-mode=pod") {
		t.Fatalf("want the debug-outside-pod error, got %v", err)
	}
}

func TestRenderValuesRequiresHelm(t *testing.T) {
	newFakeBin(t)
	err := runC8s(t, "render-values", "--cvm-mode=node", "--resolve-digests=false")
	if err == nil || !strings.Contains(err.Error(), "helm CLI not found") {
		t.Fatalf("want a helm-not-found error, got %v", err)
	}
}

// A GitOps consumer must get the same hosted-lane admission default an install
// renders: the bundle is the whole policy a HelmRelease applies, and a
// digest-only one denies the provider's own platform pods.
func TestRenderValuesHostedLaneExemptNamespaces(t *testing.T) {
	for _, tc := range []struct {
		cvmMode string
		want    any
	}{
		{"aks", []any{"kube-system"}},
		{"gke", []any{"kube-system"}},
		{"pod", []any{"kube-system"}},
		// node's baked floor already carries the system digests.
		{"node", nil},
	} {
		t.Run(tc.cvmMode, func(t *testing.T) {
			f := newFakeBin(t)
			f.tool(t, "helm", helmShowValuesBody)
			var err error
			out := captureStdout(t, func() {
				err = runC8s(t, "render-values", "--cvm-mode="+tc.cvmMode, "--resolve-digests=false")
			})
			if err != nil {
				t.Fatalf("render-values: %v", err)
			}
			var tree map[string]any
			if err := yaml.Unmarshal([]byte(out), &tree); err != nil {
				t.Fatalf("output is not a values.yaml: %v\n%s", err, out)
			}
			policy, _ := treeAt(t, tree, "nriImagePolicy").(map[string]any)["policy"].(map[string]any)
			got := policy["exemptNamespaces"]
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("nriImagePolicy.policy.exemptNamespaces = %#v, want %#v", got, tc.want)
			}
		})
	}
}
