name: govulncheck

on:
  workflow_dispatch:
  schedule:
    - cron: "22 16 1,15 * *"
  push:
    branches: [main]
    tags: ['v*']
    paths: &go-paths
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "go.work.sum"
      - ".github/workflows/govulncheck.yml"
  pull_request:
    paths: *go-paths

concurrency:
  group: ci-${{ github.ref }}-govulncheck
  cancel-in-progress: true

permissions:
  contents: read

jobs:
    govulncheck_job:
      runs-on: ubuntu-latest
      name: Run govulncheck
      steps:
        - id: govulncheck
          uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
          with:
             go-version-file: 'go.mod'
             go-package: ./...
